### ISSUE TITLE
Making game faster as go

### ISSUE THREAD

**Issue by sadrasabouri** [sepandhaghighi/mnimi#2]
#### Description
My first expectation from game was like if you won each level, you will meet higher speed level.
but it seems **Mnimi** has constant speed respected to the level.

**Comment by sepandhaghighi** [comment]
@sadrasabouri Thanks for your comment, **Mnimi** speed is not constant but you are right its slow, I will solve it ;-)
* Now speed step is 100ms

**Comment by sepandhaghighi** [comment]
@sadrasabouri 
I think now it's okay ;-)

**Comment by sepandhaghighi** [comment]
@sadrasabouri 
Please check this issue again ;-)

**Comment by sadrasabouri** [comment]
> @sadrasabouri
> Please check this issue again ;-)

Sorry for late response :disappointed: 
I've checked it, and it seems it can be more faster and for another suggestion can you remove the `Go` time before start or just decrease it's time duration?

**Comment by sepandhaghighi** [comment]
> > @sadrasabouri
> > Please check this issue again ;-)
> 
> Sorry for late response 😞
> I've checked it, and it seems it can be more faster and for another suggestion can you remove the `Go` time before start or just decrease it's time duration?

No problem ;-)
I decreased `goDelay` by 600 ms and `levelShowDelay` by 300 ms.

**Comment by sadrasabouri** [comment]
> > > @sadrasabouri
> > > Please check this issue again ;-)
> > 
> > 
> > Sorry for late response disappointed
> > I've checked it, and it seems it can be more faster and for another suggestion can you remove the `Go` time before start or just decrease it's time duration?
> 
> No problem ;-)
> I decreased `goDelay` by 600 ms and `levelShowDelay` by 300 ms.

It seems better now
thank you
